### ISSUE TITLE
Zheng assigns himself issues

### ISSUE THREAD

**Issue by buckmaxwell** [LeahK/CowCareMobileApplication#11]
Hey Zheng @liu1372 , can you please assign yourself some issues here? After you are done assigning issues to yourself please close this issue.  I will wait for you and @LeahK  to assign yourselves issues before I assign myself.  

Thanks!
-Max

**Comment by liu1372** [comment]
Hi, Max
I just pick some issues assigned to myself, should I close these issues
now? Or leave it until I finish coding?

Thanks!
Zheng

**Comment by buckmaxwell** [comment]
Thanks for assigning your issues Zheng! You should keep them open until you are done coding for them.  But you can close this one since you've finished it haha

**Comment by liu1372** [comment]
Just assigned issues
