### ISSUE TITLE
Pressing the '+' button on screen 2, leads to screen 3

### ISSUE THREAD

**Issue by buckmaxwell** [LeahK/CowCareMobileApplication#6]
For reference on screen information see [here](https://github.com/LeahK/CowCareMobileApplication/blob/master/MockScreens.pdf). 

The plus button should lead to screen 2, passing with it an empty cow id and the top level of the default treatment plan.

**Note:** _This issue is blocked because screen 3 does not yet exist_

**Comment by liu1372** [comment]
Should done by 3.2
